name: Terraform environment deployment
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  terraform-deployment:
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: dev
      tf_dir: environments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_VARS_KEY: ${{ secrets.AWS_PARAM_STORE_TF_VARS_KEY }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
