name: Terraform environment deployment
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-dev-deployment:
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: dev
      environment-for-approval: apply-tf-plan-to-dev
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  terraform-test-deployment:
    needs:
      - terraform-dev-deployment  
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: test
      environment-for-approval: apply-tf-plan-to-test
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  approve:
    needs: 
      - terraform-test-deployment
    runs-on: ubuntu-latest
    environment: deployment-checkpoint-int
    steps:
      - name: Manual Approve Info
        run: |
          terraform -v
          echo ${{ github.triggering_actor }}
          echo ${{ github.actor }}
  terraform-int-deployment:
    needs:
      - approve
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: int
      environment-for-approval: apply-tf-plan-to-int
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  terraform-staging-deployment:
    needs:
      - terraform-int-deployment
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: staging
      environment-for-approval: apply-tf-plan-to-staging
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  prod-approval:
    needs: 
      - terraform-staging-deployment
    runs-on: ubuntu-latest
    environment: deployment-checkpoint-prod
    steps:
      - name: Manual Approve Info
        run: |
          terraform -v
          echo ${{ github.triggering_actor }}
          echo ${{ github.actor }}
  terraform-prod-deployment:
    needs:
      - prod-approval
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@main
    with:
      environment: prod
      environment-for-approval: apply-tf-plan-to-prod
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
